### ISSUE TITLE
Integrate JWT auth code 

### ISSUE THREAD

**Issue by EuclidStellar** [EuclidStellar/euclid-js#1]
Integrate JWT authentication code in this package also so that when someone downloads they get an auth ready code 

Make an empty .env in which they will only have to add their credentials

**Comment by cpwallah** [comment]
i can do this @EuclidStellar

**Comment by EuclidStellar** [comment]
@cpwallah cool then I'll assign you this issue and you can fork and start working on it and in case if you get stuck anywhere do ping me

**Comment by mk0380** [comment]
Have already done it. So please review and let me know

**Comment by EuclidStellar** [comment]
@mk0380 hi mayank I have merged the pull request after reviewing it and have made a minor change in the package.json and packag-.lock.json ie 

1.0.2 -> 1.0.3 

also add a middleware in respect to this issue to complete your last PR 
ex: 

```javascript 

const jwt = require('jsonwebtoken');
const JWT_SECRET = process.env.JWT_SECRET;

function authorization(req, res, next) {
    const token = req.headers.authorization; // this is to get the token from the header
    if (!token) {
        return res.status(401).json({ message: 'Authorization denied' });
    }
    
    try {
        const decoded = jwt.verify(token, JWT_SECRET);
        req.user = decoded.user; // this is to get the user from the token

        console.log(req.user);
        console.log(decoded);
        next();
    } catch (error) {
        console.error(error.message);
        res.status(500).json({ message: 'Server error' });
    }
}
    

module.exports = authorization;
```

so please pull before making further changes

**Comment by EuclidStellar** [comment]
@mk0380 @cpwallah  I have opened some new issues please have a look at them and contribute to them too !!

**Comment by EuclidStellar** [comment]
@mk0380 thanks mayank , you can now raise your own issue of feature you think we can implement in this package :)
this issue is completed and your PR #5 has been merged 
cheers !

**Comment by EuclidStellar** [comment]
:)
