### ISSUE TITLE
Add User model for jwt authentication with password ans username 

### ISSUE THREAD

**Issue by EuclidStellar** [EuclidStellar/euclid-js#3]
Make a User model of user with username/email and password ( need to be hashed using bycryptjs ) along with addition of user's local mongoDB url in .env 

example of user model :

```javascript
const mongoose = require('mongoose');

const User = new mongoose.Schema({
    email: {
        type: String,
        required: true
    },
    password: {
        type: String,
        required: true
    }

    
});

module.exports = mongoose.model('User', User);
```

**Comment by cpwallah** [comment]
hello @EuclidStellar i have to make new file using node index .js and then add this model and can you tell me why we do this thing bcz i see that we can make many files under this any usecase ?

**Comment by EuclidStellar** [comment]
@cpwallah hi rihaan actually this project is built on the foundation to reduce iterative and boring things from nodejs which developer needs to rewrite again and again 

However you don't need to make a new index.js 

What you have to do is to make a new model.js file In the model folder under src 
And create this 

In future I'm looking to make this as a package that will give users an authentication code already written so that they can skip the authentication and authorisation part of their backend while building something cool

**Comment by cpwallah** [comment]
@EuclidStellar  got it made a pr

**Comment by EuclidStellar** [comment]
cool hey can can you also add middleware authorization code that i mentioned in issue #1 raise a PR for that issue 

and the next time you raise PR please mention issue ticket number on top of PR description 

ex :

#[issue_ticket_number ]

**Comment by mk0380** [comment]
I have made the PR #1 , please do check and let me know

**Comment by cpwallah** [comment]
made a pr #7 @EuclidStellar
